Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -40,7 +40,15 @@ jobs:
           tags: ${{ secrets.REGISTRY_ENDPOINT }}/${{ secrets.REGISTRY_LABEL }}/km-httpbin:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}
       - 
         name: Set env
-        run: echo "IMAGE=${{ secrets.REGISTRY_ENDPOINT }}/${{ secrets.REGISTRY_LABEL }}/km-httpbin:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}" >> $GITHUB_ENV    
+        run: |
+          echo "IMAGE=${{ secrets.REGISTRY_ENDPOINT }}/${{ secrets.REGISTRY_LABEL }}/km-httpbin:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}" >> $GITHUB_ENV
+          echo "RCTL_REST_ENDPOINT=${{ secrets.RCTL_REST_ENDPOINT }}" >> $GITHUB_ENV
+          echo "RCTL_API_KEY=${{ secrets.RCTL_API_KEY }}" >> $GITHUB_ENV
+          echo "RCTL_API_SECRET=${{ secrets.RCTL_API_SECRET }}" >> $GITHUB_ENV  
+          echo "RCTL_PROJECT=${{ secrets.RCTL_PROJECT }}" >> $GITHUB_ENV
+          echo "WORKLOAD_NAME=demo-app-gh-action" >> $GITHUB_ENV
+          echo "WORKLOAD_NAMESPACE=demo-gh" >> $GITHUB_ENV      
+    
       - 
         name: update image in the deployment
         shell: bash
@@ -54,3 +62,49 @@ jobs:
           author_email: nani.36@gmail.com
           message: 'updating image tag'
           add: 'httpbin-deployment.yml'
+          
+      -
+        name: Deploy Workload
+        run: |
+          wget -q https://s3-us-west-2.amazonaws.com/rafay-prod-cli/publish/rctl-linux-amd64.tar.bz2
+          tar -xf rctl-linux-amd64.tar.bz2
+          chmod 0755 rctl
+          LookupWorkload () {
+          local workload match="$1"
+          shift
+          for workload; do [[ "$workload" == "$match" ]] && return 0; done
+          return 1
+          }
+          ./rctl namespace list > /tmp/namespace
+          grep -i $WORKLOAD_NAMESPACE /tmp/namespace > /dev/null 2>&1
+          if [ $? -eq 1 ]; then
+            ./rctl create namespace $WORKLOAD_NAMESPACE
+          fi
+          rm /tmp/namespace
+          wl_tmp=`./rctl workload list -o json | jq '.result[]|.name' |cut -d'"' -f2`
+          WL_TMP_ARRAY=( $wl_tmp )
+          set +e
+          LookupWorkload $WORKLOAD_NAME "${WL_TMP_ARRAY[@]}"
+          if [ $? -eq 1 ]; then
+            set -e
+            ./rctl create workload ./httpbin-spec.yml
+          else
+            ./rctl update workload ./httpbin-spec.yml
+          fi
+          ./rctl publish workload $WORKLOAD_NAME
+          workload_status="Not Ready"
+          workload_status_iterations=1
+          while [ "$workload_status" != "Ready" ];
+          do
+            workload_status=`./rctl status workload $WORKLOAD_NAME -o json|jq .result[].status|tr -d '"'`
+            echo $workload_status
+            sleep 30
+            if [ $workload_status_iterations -ge 30 ]; then
+              break
+            fi
+            if [ "$workload_status" = "Failed" ]; then
+              echo "Workload Deployment Failed"
+            break
+            fi
+            workload_status_iterations=$((workload_status_iterations+1))
+          done
